//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NowNotes_Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NowNotes_Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to set NowNotes to launch on startup?.
        /// </summary>
        public static string Do_you_want_to_set_NowNotes_to {
            get {
                return ResourceManager.GetString("Do_you_want_to_set_NowNotes_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Launch on Startup.
        /// </summary>
        public static string Launch_on_Startup {
            get {
                return ResourceManager.GetString("Launch_on_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Note saved and cleared..
        /// </summary>
        public static string Note_saved_and_cleared {
            get {
                return ResourceManager.GetString("Note_saved_and_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rename Note.
        /// </summary>
        public static string Rename_Note {
            get {
                return ResourceManager.GetString("Rename_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The note wasn&apos;t able to be opened because another app has the internal note file opened..
        /// </summary>
        public static string The_note_wasn_t_able_to_be_ope {
            get {
                return ResourceManager.GetString("The_note_wasn_t_able_to_be_ope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The note wasn&apos;t able to be renamed and saved because another app has the internal note file opened..
        /// </summary>
        public static string The_note_wasn_t_able_to_be_ren {
            get {
                return ResourceManager.GetString("The_note_wasn_t_able_to_be_ren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The note wasn&apos;t able to be saved because another app has the internal note file opened..
        /// </summary>
        public static string The_note_wasn_t_able_to_be_sav {
            get {
                return ResourceManager.GetString("The_note_wasn_t_able_to_be_sav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The opened note has been deleted..
        /// </summary>
        public static string The_opened_note_has_been_delet {
            get {
                return ResourceManager.GetString("The_opened_note_has_been_delet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There&apos;s an update available for NowNotes. Do you want to install it?.
        /// </summary>
        public static string There_s_an_update_available_fo {
            get {
                return ResourceManager.GetString("There_s_an_update_available_fo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Untitled - .
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Available.
        /// </summary>
        public static string Update_Available {
            get {
                return ResourceManager.GetString("Update_Available", resourceCulture);
            }
        }
    }
}
